name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test Stuff
    runs-on: ubuntu-latest
    steps:
      - name: VyOS
        uses: foltik/vyos-docker-test@v1
      - name: Test Thing
        run: "curl -k -X POST https://localhost:443/retrieve -F data='{\"op\": \"showConfig\", \"path\": []}' -F key='vyos'"
